### PR TITLE
brew bump: add prerelease exception

### PR DESCRIPTION
**Pull request by toobuntu**
Ugh. Please delete the release and trigger the build again.

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Thanks but I did it already :P 
https://github.com/PikachuEXE/homebrew-FreeTube/commit/96fcbd8287db2f0516c1b9fd0d9548851f7aaacf

**Comment by toobuntu** [comment]
Strange, though, that the action still uses a workflow file with the v--and fails--even after your commit to master.

The good news is that it _is_ being triggered.

**Comment by PikachuEXE** [comment]
Maybe use this PR to fix new error I mentioned in 
https://github.com/PikachuEXE/homebrew-FreeTube/pull/13#issuecomment-2017071609

**Comment by toobuntu** [comment]
> Maybe use this PR to fix new error I mentioned in [#13 (comment)](https://github.com/PikachuEXE/homebrew-FreeTube/pull/13#issuecomment-2017071609)

Okay. Let's see if this does it.

**Comment by PikachuEXE** [comment]
Oops I did it again - -|||
https://github.com/PikachuEXE/homebrew-FreeTube/pull/13#issuecomment-2017079053

Anyway still fail maybe it needs extra permission?
Checking

**Comment by PikachuEXE** [comment]
It's getting user info in https://github.com/eugenesvk/action-homebrew-bump-cask/blob/master/main.rb#L70

My guess is that specifying permissions removes some default permissions so it can't read user info

**Pull request closed without merging**
