### PR TITLE
ci: prepare GitHub Actions infrastructure

### PR DESCRIPTION
**Pull request by toobuntu**
This PR is intended to prepare this repository for upcoming GitHub Actions (GHA) workflows, particularly, the automated build and release of FreeTube for Apple Silicon.

- dependabot.yml: Add automated version updates of GHA dependencies.
- publish.yml: Skip formula-related steps for cask-only tap
- tests.yml: Skip formula-related steps for cask-only tap
- LICENSE: The macos-14 GHA runner is free only for open source projects
- pre-commit: Add an optional Git pre-commit hook which runs actionlint, for use by contributors on their local systems
- update-actionlint-workflow.yml: Add actionlint GHA workflow and configuration from upstream Homebrew/brew repository. actionlint is a linter for GHA workflow files.

---

**Important**: update-actionlint-workflow.yml uses [peter-evans/create-pull-request](https://github.com/peter-evans/create-pull-request/) to open a PR if the upstream actionlint configuration has changed. This action requires:
1. **[Permissions](https://github.com/peter-evans/create-pull-request/?tab=readme-ov-file#workflow-permissions)**:
   > For this action to work you must explicitly allow GitHub Actions to create pull requests. This setting can be found in a repository's settings under Actions > General > Workflow permissions.
1. The workflows installed by default when running `brew tap-new` includes tests.yml, which runs `on: push` and `on: pull_request` targets. 
   > If you want pull requests created by this action to trigger an `on: push` or `on: pull_request` workflow then you cannot use the default `GITHUB_TOKEN`. See the [documentation here](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs) for workarounds. ([Source](https://github.com/peter-evans/create-pull-request/tree/main?tab=readme-ov-file#action-inputs))  

   The simplest, and GitHub-recommended, solution is to
   > Use a `repo` scoped [Personal Access Token (PAT)](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) created on an account that has write access to the repository that pull requests are being created in. This is the standard workaround and [recommended by GitHub](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow). However, the PAT cannot be scoped to a specific repository so the token becomes a very sensitive secret. If this is a concern, the PAT can instead be created for a dedicated [machine account](https://docs.github.com/en/github/site-policy/github-terms-of-service#3-account-requirements) that has collaborator access to the repository. Also note that because the account that owns the PAT will be the creator of pull requests, that user account will be unable to perform actions such as request changes or approve the pull request.[^workarounds]

   ```bash
   # Create token with repo scope
   https://github.com/settings/tokens/new?scopes=repo&description=create-pr

   # Store the token as a repository secret
   ```

   **This will then require a one-time edit to the workflow file referencing the variable for that secret.**

   The most realistic alternative is to 
   > Use a [GitHub App to generate a token](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens) that can be used with this action. GitHub App generated tokens are more secure than using a PAT because GitHub App access permissions can be set with finer granularity and are scoped to only repositories where the App is installed. This method will trigger both `on: push` and `on: pull_request` workflows.[^workarounds]

   **This will then require a one-time edit to the workflow to use [tibdex/github-app-token](https://github.com/tibdex/github-app-token) to generate a token for use with this action.**

[^workarounds]: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#workarounds-to-trigger-further-workflow-runs

---

So it basically seems to be a decision of:
1. Don't care about running tests.yml -> no action required -> uses the default token
1. Do care about running tests.yml -> take action -> use a GitHub App

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Thanks for your effort ;)

Let's not run tests (which requires more manual changes and I am not sure if it's worth the effort)
Or we can run tests manually by editing `tests.yml` (If we really need to run it)
I have updated the Actions > General > Workflow permission to allow PR creation

Anything else?

**Comment by toobuntu** [comment]
That seems reasonable to me. The tests.yml workflow would still run on other PRs, just not this automated one. And in the case of this automated one, well, we are pulling in files from Homebrew, which has the actionlint workflow to test it. So it seems we are well covered.

---

If it were only that simple.

1. The forthcoming integration with upstream consists of two workflows—one upstream (freetube), triggered on published releases, and another downstream (here), triggered by a `repository_dispatch` event from upstream. A token is required to dispatch to a remote repo. Relocating the Homebrew Tap to the upstream account would enable the use of a fine-grained PAT, ensuring more controlled access. I am not sure if this repo is here to stay or will eventually be moved upstream, or whether you would want to give upstream a PAT with `public_repo` scope that has access to all of your public repos. So if it stays here I think the GitHub App approach would be the most likely way to handle it for that workflow, and was sort of hoping we could test it out with this workflow where it doesn't really matter so much.

   In short, upstream notifies the Homebrew Tap of the `tag_name` and `node_version` when it publishes a release. This repo then uses that info to build and release the app for macOS arm64.

1. I added a commit with some fixup and cleanups:

   - For one thing, I only just discovered that the `ubuntu-latest` runner has an older version of cURL which does not yet have the `--clobber` option. That functionality can be handled several ways (e.g., write to a temp file and move the temp file where we want, install a newer version of curl, change to a different runner which has a newer version of curl). I changed the runner to `macos-14`.

      FYI, workflows can be tested, at least to some degree, in [Act](https://github.com/nektos/act "https://github.com/nektos/act"). On my Mac, this looked like:

      ```bash
      brew install act
      brew install --no-quarantine docker
      open -a Docker
      # curl error
      act --container-architecture linux/amd64 --job update-workflow
      # Edit workflow to change runner to macOS-14
      sed -i '' '/runs-on: ubuntu-latest/ s/ubuntu-latest/macos-14/' .github/workflows/update-actionlint-workflow.yml
      # curl success
      act --platform macos-14=-self-hosted --job update-workflow
      ```

      I also tested passing `--secret GITHUB_TOKEN="$(gh auth token)"` to test the create-pull-request part, with success.

   - While there, I also added the `--remove-on-error` curl option and did some minor nitpicky clean ups.

**Review by PikachuEXE — APPROVED** [review]
Just merge and test? (is there anything can be run even manually though

**Comment by toobuntu** [comment]
Yes, just merge.

You can then either wait for it to run on schedule by cron, or trigger the workflow manually by following the steps shown here: https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow?tool=webui

If it succeeds, you should have a new PR wanting to add the three actionlint-related files and three ETags.

How would you like to handle the token issue with the forthcoming workflow to build and release on dispatch, mentioned above?

**Comment by PikachuEXE** [comment]
Using GitHub App way seems better (for testing or actually used)
I think this repo is temporary (for testing) and eventually will be moved into FT organization
So better make it work in both cases (or at least easy to migrate after testing)

First run failed already :) - https://github.com/PikachuEXE/homebrew-FreeTube/actions/runs/8296636051/job/22706041724

**Comment by toobuntu** [comment]
It looks like a permissions issue: `remote: Permission to PikachuEXE/homebrew-FreeTube.git denied to github-
actions[bot].`

Screenshot 2024-03-15 at 11 31 58 AM


The create-pull-request part worked in my testing with these settings:
Screenshot 2024-03-15 at 11 27 55 AM

**Comment by PikachuEXE** [comment]
It seems PAT is still required
https://github.com/peter-evans/create-pull-request/blob/v6.0.2/docs/examples.md#keep-a-fork-up-to-date-with-its-upstream

Let me fix next week

**Comment by toobuntu** [comment]
You are right. I think I might have made a note of the requirements when I started working on this weeks ago, but with the sporadic nature of the work it got lost. My testing was indeed using a classic PAT with `repo` and `workflow` scopes.

It seems the GitHub App would need these Repository permissions:
- **`Contents`** `Access: Read & write`
- **`Pull requests`** `Access: Read & write`
- **`Workflows`** `Access: Read & write`
- **`Metadata`** `Access: Read only` (automatically selected when selecting the contents permission)

It should then be possible to use this same GitHub App to generate short-lived tokens for this workflow, and for the forthcoming ones (which are still probably going to be weeks away, unfortunately -- I won't have much time in the next couple of weeks to get them ready to submit).

**Pull request merged**
