### PR TITLE
ci: pin actions to a full length commit SHA

### PR DESCRIPTION
**Pull request by toobuntu**
Per GitHub's [security guide](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions "https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions"):
> - Pin actions to a full length commit SHA
>
>   Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload. When selecting a SHA, you should verify it is from the action's repository and not a repository fork.

This should be a non-breaking change, as Dependabot [updates comments in GitHub Actions workflows referencing action versions](https://github.blog/changelog/2022-10-31-dependabot-now-updates-comments-in-github-actions-workflows-referencing-action-versions/ "https://github.blog/changelog/2022-10-31-dependabot-now-updates-comments-in-github-actions-workflows-referencing-action-versions/"):
> GitHub Actions workflows often specify the version of an action using the commit SHA. Since commit SHAs are immutable, this ensures that Actions always picks the same version. Commit SHAs, however, are not very human friendly, so best practice is to include the semver version in a comment next to the SHA. Dependabot will now update the semver version in comments when updating Actions workflows with a commit SHA version.

Generated via [`pinact run`](https://formulae.brew.sh/formula/pinact#default "https://formulae.brew.sh/formula/pinact#default").

### CODE REVIEW

**Comment by toobuntu** [comment]
CI failure is a [known issue](https://github.com/orgs/Homebrew/discussions/5785 "https://github.com/orgs/Homebrew/discussions/5785"), though not sure why it's happening here in CI.

Running actionlint locally passes:
```sh
# gh repo sync toobuntu/homebrew-FreeTube
✓ Synced the "toobuntu:master" branch from "PikachuEXE:master"
# git pull
Already up to date.
# brew list --versions actionlint shellcheck
actionlint 1.7.5
shellcheck 0.10.0
# actionlint --verbose 2>&1 | grep --fixed-strings "Found total"
verbose: Found total 0 errors in 133 ms for .github/workflows/publish.yml
verbose: Found total 0 errors in 133 ms for .github/workflows/tests.yml
verbose: Found total 0 errors in 146 ms for .github/workflows/actionlint.yml
verbose: Found total 0 errors in 162 ms for .github/workflows/update-tap.yml
verbose: Found total 0 errors in 165 ms for .github/workflows/release-manual-trigger.yml

**Comment by PikachuEXE** [comment]
Does adding `brew install-bundler-gems --groups=all` in CI config work?

**Comment by toobuntu** [comment]
I've [reported](https://github.com/orgs/Homebrew/discussions/5833 "https://github.com/orgs/Homebrew/discussions/5833") the failure. You can subscribe and comment there to follow the discussion.

`brew install` was failing for me on CLI with the same error, too. But then it started working again. Can you try [re-running](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/re-running-workflows-and-jobs#re-running-all-the-jobs-in-a-workflow "https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/re-running-workflows-and-jobs#re-running-all-the-jobs-in-a-workflow") the workflow?

I doubt it would be advised to add that command to the workflow permanently (though [`actions/setup-homebrew`](https://github.com/Homebrew/actions/tree/master/setup-homebrew "https://github.com/Homebrew/actions/tree/master/setup-homebrew") does have the option to install Ruby gems). I mean, why should all the gems be needed just to install two formulae?

**Comment by PikachuEXE** [comment]
Rerun but same error

**Comment by toobuntu** [comment]
The failing workflow here simply runs actionlint, and actionlint passes when run locally. Let's deal with the actionlint stuff in a separate issue/pr. Is there anything to block merging this pr as-is?

**Pull request merged**
